version: '3.3'
services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile.txt
    container_name: php73
    depends_on: 
      - db
    volumes:
      - .:/var/www/html/ 
    networks:
      php_mysql_network:
    ports:
      - 8000:80
  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDatabase 
      MYSQL_USER: user1 
      MYSQL_PASSWORD: root
    networks:
      php_mysql_network:
#    ports:
#      - 6033:3306
      
networks:
  php_mysql_network:
  
    
      
      
      
    
      